FROM python:3.12

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ./app/data_ingestion.py .
COPY ./app/db.py .
COPY ./app/config.py .

CMD ["sh", "-c", "python data_ingestion.py"]

